CREATE TABLE  `user`( 
 `id` INT NOT NULL AUTO_INCREMENT,
`nickName` VARCHAR(50) DEFAULT  NULL ,
`password` VARCHAR(50) DEFAULT  NULL ,
`created` DATETIME DEFAULT  NULL,
`lastLogin` DATETIME DEFAULT  NULL,
PRIMARY KEY (`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;
CREATE TABLE `blog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `content` LONGTEXT,
  `created` DATETIME NOT NULL,
  `lastModification` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '默认取当前时间',
  `status` TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `blogComment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
 `blog_id` INT NOT NULL,
  `content` LONGTEXT,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB  DEFAULT CHARSET=utf8mb4;
`blogComment``user`